# Port of HTTP(S) proxy server on the local end
# port: 7890

# Port of SOCKS5 proxy server on the local end
# socks-port: 7891

# Transparent proxy server port for Linux and macOS (Redirect TCP and TProxy UDP)
# redir-port: 7892

# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893

# HTTP(S) and SOCKS4(A)/SOCKS5 server on the same port
mixed-port: 7890

# authentication of local SOCKS5/HTTP(S) server
# authentication:
#  - "user1:pass1"
#  - "user2:pass2"

# Set to true to allow connections to the local-end server from
# other LAN IP addresses
allow-lan: false

# This is only applicable when `allow-lan` is `true`
# '*': bind all IP addresses
# 192.168.122.11: bind a single IPv4 address
# "[aaaa::a8aa:ff:fe09:57d8]": bind a single IPv6 address
bind-address: '*'

# Clash router working mode
# rule: rule-based packet routing
# global: all packets will be forwarded to a single endpoint
# direct: directly forward the packets to the Internet
mode: rule

# Clash by default prints logs to STDOUT
# info / warning / error / debug / silent
log-level: info

# When set to false, resolver won't translate hostnames to IPv6 addresses
ipv6: false

# RESTful web API listening address
external-controller: 127.0.0.1:9090

# A relative path to the configuration directory or an absolute path to a
# directory in which you put some static web resource. Clash core will then
# serve it at `http://{{external-controller}}/ui`.
external-ui: yacd

# Secret for the RESTful API (optional)
# Authenticate by spedifying HTTP header `Authorization: Bearer ${secret}`
# ALWAYS set a secret if RESTful API is listening on 0.0.0.0
# secret: ""

# Outbound interface name
# interface-name: en0

# Static hosts for DNS server and connection establishment (like /etc/hosts)
#
# Wildcard hostnames are supported (e.g. *.clash.dev, *.foo.*.example.com)
# Non-wildcard domain names have a higher priority than wildcard domain names
# e.g. foo.example.com > *.example.com > .example.com
# P.S. +.foo.com equals to .foo.com and foo.com
hosts:
  # '*.clash.dev': 127.0.0.1
  # '.dev': 127.0.0.1
  # 'alpha.clash.dev': '::1'

profile:
  # Store the `select` results in $HOME/.config/clash/.cache
  # set false If you don't want this behavior
  # when two different configurations have groups with the same name, the selected values are shared
  store-selected: true

# DNS server settings
# This section is optional. When not present, the DNS server will be disabled.

# ## tun
dns:
  enable: true
  enhanced-mode: fake-ip
  nameserver:
    # ## 真实请求DNS
    - 114.114.114.114 # 真实请求DNS，可多设置几个
    # ## 国内服务器
    - 119.29.29.29    # 腾讯
    - 223.5.5.5       # 阿里
    - 180.76.76.76    # 百度
    # ## 真实请求DNS
    - 8.8.8.8
tun:
  enable: true
  stack: system # or gvisor
  dns-hijack:
  #   - 8.8.8.8:53
  #   - tcp://8.8.8.8:53
    - any:53
    - tcp://any:53
  auto-route: true # auto set global route
  auto-detect-interface: true # conflict with interface-name

proxy-groups:
  - name: "PROXY"
    type: select
    # disable-udp: true
    proxies:
      - AllFallback-aa
      - AllAuto-aa
      - AllSelect
      - SelectUs
      - SelectTor
      - NodePoolAuto-b
      - NodePoolAuto-c
      - NodePoolAuto-d
      - NodePoolAuto-z
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "RuleMode"
    type: select
    # disable-udp: true
    proxies:
      - DIRECT
      - PROXY

  - name: "AllFallback-aa"
    type: fallback
    use:
    proxies:
      - NodePoolAuto-b
      - NodePoolAuto-c
      - NodePoolAuto-d
      - NodePoolAuto-z
    # tolerance: 50
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 30

  - name: "AllAuto-aa"
    type: url-test
    use:
    proxies:
      - NodePoolAuto-b
      - NodePoolAuto-c
      - NodePoolAuto-d
      - NodePoolAuto-z
    # tolerance: 50
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 30

  - name: "AllSelect"
    type: select
    use:
      - nodepool_myfilter-ba
      - nodepool_myfilter-za
    proxies:
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "SelectUs"
    type: select
    use:
      - nodepool_myfilter-cb
    proxies:
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "SelectTor"
    type: select
    proxies:
      - tor
    # lazy: true
    # url: 'http://www.gstatic.com/generate_204'
    url: 'https://www.google.com'
    interval: 300

  - name: "NodePoolAuto-b"
    type: url-test
    use:
      - nodepool_myfilter-ba
    proxies:
    # tolerance: 50
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-c"
    type: url-test
    use:
      - nodepool_myfilter-ca
      - nodepool_myfilter-cb
    proxies:
    # tolerance: 50
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-d"
    type: url-test
    use:
      - nodepool_myfilter-da
    proxies:
    # tolerance: 50
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

  - name: "NodePoolAuto-z"
    type: url-test
    use:
      - nodepool_myfilter-za
    proxies:
    # tolerance: 50
    # lazy: true
    url: 'http://www.gstatic.com/generate_204'
    interval: 300

proxies:
  - name: "tor"
    type: socks5
    server: 127.0.0.1
    port: 9150
    # username: username
    # password: password
    # tls: true
    # skip-cert-verify: true
    # udp: true

  # - name: "http"
  #   type: http
  #   server: server
  #   port: 443
  #   # username: username
  #   # password: password
  #   # tls: true # https
  #   # skip-cert-verify: true
  #   # sni: custom.com

proxy-providers:
  nodepool_myfilter-ba:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?c=CN,HK,TW,MO"
    path: ./proxy-providers/nodepool/myfilter-ba.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

  nodepool_myfilter-ca:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?type=vmess,ssr,trojan&c=SG,CA,RU,AU,CH,DE,FR,GD,NL,JP"
    path: ./proxy-providers/nodepool/myfilter-ca.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

  nodepool_myfilter-cb:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?type=vmess,ssr,trojan&c=US"
    path: ./proxy-providers/nodepool/myfilter-cb.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

  nodepool_myfilter-da:
    type: http
    url: "https://sspool.herokuapp.com/clash/proxies?type=vmess,ssr,trojan&c=AD,AE,AF,AG,AI,AL,AM,AN,AO,AQ,AR,ARPA,AS,AT,AW,AZ,BA,BB,BD,BE,BF,BG,BH,BI,BJ,BM,BN,BO,BR,BS,BT,BV,BW,BY,BZ,CC,CF,CD,CG,CI,CK,CL,CM,CO,COM,CR,CS,CU,CV,CX,CY,CZ,DJ,DK,DM,DO,DZ,EC,EDU,EE,EG,EH,ER,ES,ET,FI,FJ,FK,FM,FO,FX,GA,GB,GE,GF,GH,GI,GL,GM,GN,GOV,GP,GQ,GR,GS,GT,GU,GW,GY,HM,HN,HR,HT,HU,ID,IE,IL,IN,INT,IO,IQ,IR,IS,IT,JM,JO,KE,KG,KH,KI,KM,KN,KP,KR,KW,KY,KZ,LA,LB,LC,LI,LK,LR,LS,LT,LU,LV,LY,MA,MC,MD,MG,MH,MIL,MK,ML,MM,MN,MP,MQ,MR,MS,MT,MU,MV,MW,MX,MY,MZ,NA,NATO,NC,NE,NET,NF,NG,NI,NO,NP,NR,NT,NU,NZ,OM,ORG,PA,PE,PF,PG,PH,PK,PL,PM,PN,PR,PT,PW,PY,QA,RE,RO,RW,SA,SB,SC,SD,SE,SH,SI,SJ,SK,SL,SM,SN,SO,SR,ST,SU,SV,SY,SZ,TC,TD,TF,TG,TH,TJ,TK,TM,TN,TO,TP,TR,TT,TV,TZ,UA,UG,UK,UM,UY,UZ,VA,VC,VE,VG,VI,VN,VU,WF,WS,YE,YT,YU,ZA,ZM,ZR,ZW"
    path: ./proxy-providers/nodepool/myfilter-da.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

  nodepool_myfilter-za:
    type: http
    url: "https://proxies.bihai.cf/clash/proxies?filter=r"
    path: ./proxy-providers/nodepool/myfilter-za.yaml
    interval: 3600
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://www.gstatic.com/generate_204

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

rules:
  # # My Mode
  # ## Custom
  # ### App
  # - PROCESS-NAME,v2ray,DIRECT
  # - PROCESS-NAME,v2ray.exe,DIRECT
  # ### Domain
  - DOMAIN,raw.githubusercontent.com,PROXY
  # #### Basic
  - DOMAIN-SUFFIX,hcaptcha.com,PROXY
  - DOMAIN-SUFFIX,captcha.website,PROXY

  # #### Common
  - DOMAIN-SUFFIX,altapps.net,PROXY

  # #### 科学上网
  - DOMAIN,cdn.jsdelivr.net,PROXY
  - DOMAIN-SUFFIX,v2rayse.com,PROXY
  - DOMAIN-SUFFIX,herokuapp.com,PROXY
  # ##### 订阅转换
  - DOMAIN-SUFFIX,bianyuan.xyz,PROXY
  - DOMAIN-SUFFIX,suo.yt,PROXY
  - DOMAIN-SUFFIX,sub.xeton.dev,PROXY
  - DOMAIN-SUFFIX,pub-api-1.bianyuan.xyz,PROXY
  - DOMAIN-SUFFIX,sub.id9.cc,PROXY
  # ##### Others
  - DOMAIN-SUFFIX,bulink.xyz,PROXY
  - DOMAIN-SUFFIX,yugogo.xyz,PROXY
  - DOMAIN-SUFFIX,sspool.nl,PROXY
  - DOMAIN-SUFFIX,bihai.cf,PROXY
  - DOMAIN-SUFFIX,kingfu.cf,PROXY
  - DOMAIN-SUFFIX,swyjq.com,PROXY
  - DOMAIN-SUFFIX,hax.co.id,PROXY
  - DOMAIN-SUFFIX,niaoyun.me,PROXY
  - DOMAIN-SUFFIX,niaoyun-a.xyz,PROXY
  - DOMAIN-SUFFIX,www.v2gyy.com,PROXY
  - DOMAIN-SUFFIX,niaocloud-rss.com,PROXY
  - DOMAIN-SUFFIX,xdmyyds.com,PROXY
  - DOMAIN-SUFFIX,55k.buzz,PROXY
  - DOMAIN-SUFFIX,freemycloud.me,PROXY
  - DOMAIN-SUFFIX,ssthy.com,PROXY
  - DOMAIN-SUFFIX,888888.sbs,PROXY
  - DOMAIN-SUFFIX,juzi000.com,PROXY
  - DOMAIN-SUFFIX,juzicloud.net,PROXY
  - DOMAIN-SUFFIX,cv2.us,PROXY

  # #### Temp
  - DOMAIN-SUFFIX,bootcdn.net,PROXY
  - DOMAIN-SUFFIX,ytimg.com,PROXY
  - DOMAIN-SUFFIX,lbyczf.com,PROXY
  - DOMAIN-SUFFIX,buyvm.net,PROXY
  - DOMAIN-SUFFIX,zxfast.com,PROXY
  - DOMAIN-SUFFIX,happykidsforum.org,PROXY
  - DOMAIN-SUFFIX,tiktokcdn.com,PROXY
  - DOMAIN-SUFFIX,truthsocial.com,PROXY
  - DOMAIN-SUFFIX,welink345.com,PROXY
  - DOMAIN-SUFFIX,redditmail.com,PROXY
  - DOMAIN-SUFFIX,rutracker.org,PROXY
  - DOMAIN-SUFFIX,beautyleg.com,PROXY
  - DOMAIN-SUFFIX,limbopro.com,PROXY

  # ### Domain KeyWord
  - DOMAIN-KEYWORD,speedtest,PROXY

  # ## No Custom
  - RULE-SET,applications,DIRECT

  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT

  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,tld-not-cn,PROXY
  - RULE-SET,gfw,PROXY
  - RULE-SET,greatfire,PROXY
  - RULE-SET,telegramcidr,PROXY

  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,direct,DIRECT
  - RULE-SET,lancidr,DIRECT
  - RULE-SET,cncidr,DIRECT

  - GEOIP,LAN,DIRECT
  - GEOIP,CN,DIRECT

  - MATCH,RuleMode
